### ISSUE TITLE
Default config + container starts but DNS not resolved

### ISSUE THREAD

**Issue by smehdux** [LemonLDAPNG/lemonldap-ng-docker#49]
Hi,

I've followed the ReadMe file to run a container on my laptop, I've modified my hosts file to match the default configuration, the container starts but when browsing http://auth.example.com I get an error (DNS not resolved).

 **Le site demandé "auth.example.com" n'a pas pu être résolu par le DNS. 
Translation to english => The requested site "auth.example.com" could not be resolved by DNS.**

Same think with docker-compose with/without custom domain.

Below my config:

```
#hosts file
127.0.0.1 auth.example.com manager.example.com reload.example.com test1.example.com test2.example.com 

```

```
#command to run docker 
sudo docker run -d -e LOGLEVEL=debug -p 80:80 coudot/lemonldap-ng:2.17.2

```

thank you in advance.

Mehdi

**Comment by smehdux** [comment]
Hi,
Finally I've managed to run it with a custom docker-compose file (below).
/etc/hosts should be update to add the *.lemon.local hosts.


```
version: "3.3"
 
  lemonldap:
    image: coudot/lemonldap-ng:2.17.2
    restart: always
    networks:
      - interne
    ports:
      - 80:80
      - 9000:9000
    environment:
      - SSODOMAIN=lemon.local
      - PORTAL_HOSTNAME=portal.lemon.local
      - MANAGER_HOSTNAME=manager.lemon.local
      - HANDLER_HOSTNAME=handler.lemon.local
      - TEST1_HOSTNAME=test1.lemon.local
      - TEST2_HOSTNAME=test2.lemon.local
      - FASTCGI_LISTEN_PORT=9000
      - LOGLEVEL=debug

networks:
  interne:
```
